// authContext
export const USER_AUTHENTICADED = 'USER_AUTHENTICADED'
export const USER_UNAUTHENTICADED='USER_UNAUTHENTICADED'
export const SUCCESSFUL_REGISTRATION = 'SUCCESSFUL_REGISTRATION'
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION'

export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SIGN_OUT = 'SIGN_OUT'

// appContext
export const CLEAR_STATE = 'CLEAR_STATE'
export const UPLOAD_FILE = 'UPLOAD_FILE'

export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR'

export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS'
export const CREATE_LINK_ERROR = 'CREATE_LINK_ERROR'

export const ADD_DOWNLOADS = 'ADD_DOWNLOADS'
export const ADD_PASSWORD = 'ADD_PASSWORD'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'