// authContext
export const USER_AUTHENTICADED = 'USER_AUTHENTICADED'
export const SUCCESSFUL_REGISTRATION = 'SUCCESSFUL_REGISTRATION'
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION'

export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SIGN_OUT = 'SIGN_OUT'

// appContext
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR'

export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS'
export const CREATE_LINK_ERROR = 'CREATE_LINK_ERROR'

export const SHOW_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'