export const USER_AUTHENTICADED = 'USER_AUTHENTICADED'
export const SUCCESSFUL_REGISTRATION = 'SUCCESSFUL_REGISTRATION'
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION'

export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SIGN_OUT = 'SIGN_OUT'

export const CLEAR_ALERT = 'CLEAR_ALERT'